
## transaction log store, only used in seata-server
store:

  ## store mode: file、db、redis
  mode: file
  ## file store property
  file:
    ## store location dir
    dir: sessionStore
    # branch session size , if exceeded first try compress lockkey, still exceeded throws exceptions
    maxBranchSessionSize: 16384
    # globe session size , if exceeded throws exceptions
    maxGlobalSessionSize: 512
    # file buffer size , if exceeded allocate new buffer
    fileWriteBufferCacheSize: 16384
    # when recover batch read size
    sessionReloadReadSize: 100
    # async, sync
    flushDiskMode: async
  ## database store property
  db:
    ## the implement of javax.sql.DataSource, such as DruidDataSource(druid)/BasicDataSource(dbcp)/HikariDataSource(hikari) etc.
    datasource: druid
    ## mysql/oracle/postgresql/h2/oceanbase etc.
    dbType: mysql
    driverClassName: com.mysql.jdbc.Driver
    ## if using mysql to store the data, recommend add rewriteBatchedStatements=true in jdbc connection param
    url: jdbc:mysql://127.0.0.1:3306/seata?rewriteBatchedStatements=true
    user: mysql
    password: mysql
    minConn: 5
    maxConn: 100
    globalTable: global_table
    branchTable: branch_table
    lockTable: lock_table
    queryLimit: 100
    maxWait: 5000
  ## redis store property
  redis:
    host: 127.0.0.1
    port: 6379
    password: ""
    database: 0
    minConn: 1
    maxConn: 10
    queryLimit: 100

